---
title: "Supplementary data analysis"
author: "Pratibha Panwar"
date: "2025-09-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

```{r}
library(SpatialDatasets)
library(SpatialExperiment)
library(dplyr)

library(scater)
library(ggplot2)

library(clustSIGNAL)
```

# Supplementary material

## Assessing data sparssity

```{r}
#### Sparsity of raw counts

# spe objects of downloaded data
spe_me <- readRDS("./spe_mouseEmbryo.Rds")
spe_br <- readRDS("./spe_breastCancer.Rds")
spe_lc <- readRDS("./spe_lungNSCLC.Rds")
spe_mh <- readRDS("./spe_mouseHypothal.Rds")
spe_oc <- readRDS("./spe_ovarianCancer.Rds")
spe_coad <- readRDS("./spe_colonCancer.Rds")

spe_list <- c("SeqFISH" = spe_me, "Xenium" = spe_br, "CosMx" = spe_lc, 
              "MERFISH" = spe_mh, "Stere-seq" = spe_oc, "VisiumHD" = spe_coad)

sparse_c_df <- imap_dfr(spe_list, function(spe, tech) {
  # calculating total expression values in the data
  tot_elem <- as.numeric(nrow(spe)) * as.numeric(ncol(spe))
  # calculating non-zero expression values
  nz_elem <- nnzero(counts(spe))
  # calculating percentage of non-zero expression values
  perc_nz <- (nz_elem / tot_elem) * 100
  # creating dataframe
  data.frame(Technology = tech,
             Total_counts = tot_elem,
             NonZero_counts = nz_elem,
             Percent_NonZero_counts = perc_nz)
})
saveRDS(sparse_c_df, "./data_outputs/realDataOut/sparsity_counts.Rds")


#### Sparsity of smoothed counts

# spe objects of ClustSIGNAL runs containing smoothed data
cSIGNAL_me <- readRDS("./data_outputs/benchmarkOut/spe_me_cSIGNAL.Rds")
cSIGNAL_br <- readRDS("./data_outputs/benchmarkOut/spe_br_cSIGNAL.Rds")
cSIGNAL_lc <- readRDS("./data_outputs/benchmarkOut/spe_lc_cSIGNAL.Rds")
cSIGNAL_mh <- readRDS("./data_outputs/benchmarkOut/spe_mh_cSIGNAL.Rds")
cSIGNAL_oc <- readRDS("./data_outputs/benchmarkOut/spe_oc_cSIGNAL.Rds")
cSIGNAL_coad <- readRDS("./data_outputs/benchmarkOut/spe_coad_cSIGNAL.Rds")

spe_list <- c("SeqFISH" = cSIGNAL_me, "Xenium" = cSIGNAL_br, 
              "CosMx" = cSIGNAL_lc, "MERFISH" = cSIGNAL_mh, 
              "Stere-seq" = cSIGNAL_oc, "VisiumHD" = cSIGNAL_coad)

sparse_s_df <- imap_dfr(spe_list, function(spe, tech) {
  # calculating total expression values in the data
  tot_elem <- as.numeric(nrow(spe)) * as.numeric(ncol(spe))
  # calculating non-zero expression values
  nz_elem <- nnzero(assay(spe, "smoothed"))
  # calculating percentage of non-zero expression values
  perc_nz <- (nz_elem / tot_elem) * 100
  # creating dataframe
  data.frame(Technology = tech,
             Total_smoothed = tot_elem,
             NonZero_smoothed = nz_elem,
             Percent_NonZero_smoothed = perc_nz)
})
saveRDS(sparse_s_df, "./data_outputs/realDataOut/sparsity_smoothed.Rds")
```

## Keren et al, 2018 data analysis

Data were extracted as a spatial proteomics spe object from SpatialDatasets 
package.

```{r}
#### data extraction and pre-processing

# library(SpatialDatasets)
speK <- spe_Keren_2018() # extracted from SpatialDatasets

# converting intensity assay data frame to matrix
assay(speK, "intensities") <- as.matrix(assay(speK, "intensities"))

# identifying control metal ions and nuclear stains
control_features <- c("Na", "Si", "P", "Ca", "Fe", "Ta", "Au", "Background")
nuclear_stains <- c("dsDNA", "H3K9ac", "H3K27me3")

# removing metal ion and nuclear controls
speK <- speK[!(rownames(speK) %in% append(control_features, nuclear_stains)), ]

# creating unique cellIDs
speK$uniqueID <- paste0("Cell_", speK$imageID, "_", speK$CellID)
colnames(speK) <- speK$uniqueID
rownames(colData(speK)) <- speK$uniqueID
rownames(spatialCoords(speK)) <- speK$uniqueID
```

```{r}
#### Generating gene expression

# Following Keren et al, 2018 protocol for converting intensity to 
# expression information
# "Expression assignment
# For each cell, for each maker, the total intensity per cell was computed. 
# Values were divided by the cell size, Arcsinh transformed, and standardized 
# across markers using std normalization."

# Normalizing by cell size
cell_size <- speK$cellSize
intensity_mat <- assay(speK, "intensities")
intensity_norm <- sweep(intensity_mat, 2, cell_size, FUN = "/")

# Arcsinh transformation of data
intensity_arcsinh <- asinh(intensity_norm)

# z-score normalisation (standardization)
intensity_z <- t(scale(t(intensity_arcsinh)))

# Storing normalised expression data in spe object
assay(speK, "expression") <- intensity_z
```

```{r}
#### Visualisation and QC check

# visualising expression
plot(density(assay(speK, "expression")))

# QC check
speK |> 
  join_features(features = rownames(speK), shape = "wide", assay = "expression") |> 
  ggplot(aes(x = CD3, colour = imageID)) + 
  geom_density() + 
  theme_classic() +
  theme(legend.position = "none")
```

```{r}
#### Running ClustSIGNAL

# checking for batch effects
set.seed(2025)
speK <- runPCA(speK, exprs_values = "expression")
speK <- runUMAP(speK, dimred = "PCA")
speK$Group <- factor(speK$Group)
speK$DONOR_NO <- factor(speK$DONOR_NO)
plotReducedDim(speK, dimred = "UMAP", color_by = "Group", scattermore = T,
               point_alpha = 1, point_size = 2) +
  scale_color_manual(values = colors)
plotReducedDim(speK, dimred = "UMAP", color_by = "DONOR_NO", scattermore = T,
               point_alpha = 1, point_size = 2) +
  scale_color_manual(values = colors)

# excluding samples with no survival data
speK <- speK[, !is.na(speK$`Survival_days_capped*`)]

set.seed(2025)
# ClustSIGNAL requires a "logcounts" assay with normalised data
assay(speK, "logcounts") <- assay(speK, "expression")
speK <- runPCA(speK)

# running ClustSIGNAL - batch effects in Group
set.seed(567)
res <- clustSIGNAL(speK, dimRed = "PCA", samples = "imageID", batch_by = TRUE, 
                   batch = "Group", threads = 8, outputs = "a")

saveRDS(res, "./data_outputs/Keren_2018/res_cSIGNAL.Rds")
```



## Benchmarking multisample analysis

```{r}
#### PASTE alignment + ClustSIGNAL analysis of mouse embryo samples ####

# PASTE applied using the script in benchmarking_PASTE.py
# Aligned coordinates = "./data_outputs/benchmarkOut/Aligned_coords_ME.csv"


## loading aligned coordinates
me_align_coords <- read.csv("./data_outputs/benchmarkOut/Aligned_coords_ME.csv")
# loading and pre-processing mouse embryo spe object
spe_me <- readRDS("./spe_mouseEmbryo.Rds") # spe object of downloaded data
spe_me <- spe_me[, spe_me$celltype_mapped_refined != "Low quality"]
spe_me$celltype_mapped_refined <- factor(spe_me$celltype_mapped_refined)

## adding aligned coordinates
# storing original coordinates with metadata
colData(spe_me) <- cbind(colData(spe_me), as.data.frame(spatialCoords(spe_me)))
# adding aligned coordinates to metadata
join_df <- left_join(as.data.frame(colData(spe_me)), me_align_coords, 
                             by = c("uniqueID" = "X"))
spe_me$x_aligned <- join_df$x_aligned
spe_me$y_aligned <- join_df$y_aligned
# adding aligned coordinates to spatial coordinates slot of spe object
spatialCoords(spe_me) <- as.matrix(colData(spe_me)[, c("x_aligned", "y_aligned")])


## running ClustSIGNAL
set.seed(567)
cSIGNAL_me <- clustSIGNAL(spe_me, samples = "embryo", outputs = "s")
saveRDS(cSIGNAL_me$spe_final, 
        file = "./data_outputs/benchmarkOut/spe_me_PASTE_cSIGNAL.Rds")
```

```{r}
#### PASTE alignment + GraphST analysis of mouse embryo samples

# PASTE applied to each dataset using the script in benchmarking_PASTE.py
# Anndata object with aligned coordinates = "./data_outputs/annDataFiles/mouse_embryo/Embryo_aligned_merged.h5ad"

# GraphST run using the script in benchmarking_GraphST.py
# Cluster labels = "./data_outputs/benchmarkOut/paste_graphst_me.csv"
```

```{r}
#### ClustSIGNAL + Harmony on lung cancer samples

spe_lc <- readRDS("./spe_lungNSCLC.Rds") # spe object of downloaded data

set.seed(567)
cSIGNAL_lc <- clustSIGNAL(spe_lc, samples = "Run_Tissue_name", threads = 16, 
                          batch = T, batch_by = "patient", outputs = "s")

saveRDS(cSIGNAL_lc$spe_final, 
        file = "./data_outputs/benchmarkOut/spe_lc_cSIGNAL_batch.Rds")
```
